version: '3'
services:
  fastapi:
    image: fastapi/mp:${DEV_VERSION}
    ports:
      - "3200:8000"
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=value
      - LOG_LEVEL=debug # Set logging level to debug
    volumes:
      - ./line-google-sheet:/app:ro ### Path source code Dev
      - logs:/var/log/fastapi
    networks:
      - internal

volumes:
  logs:
networks:
  internal:
