version: '3'
services:
  fastapi_std:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: fastapi/mp:${LIVE_VERSION}
  dev:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: fastapi/mp:${DEV_VERSION}
