version: '3'
services:
  fastapi_std:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: fastapi_std/majin:${SERVER_VERSION}
  dev:
    build:
        context: .
        dockerfile: ./Dockerfile_NOT_CMD
    image: fastapi_std/majin:dev
